version: '3'
services:
  zookeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeper
    ports:
      - "9892:9892"
      - "9894:9894"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEPER_CONNECT: zookeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9892,OUTSIDE://:9894
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9892,OUTSIDE://host.docker.internal:9894
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.insternal:172.17.0.1"

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c
        "sleep 5s &&
        kafka-topics --create --topic=route.new-direction --if-not-exists --bootstrap-server=kafka:9892 &&
        kafka-topics --create --topic=route.new-position --if-not-exists --bootstrap-server=kafka:9892"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9821:9821"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9892'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9821%
      